Resources:
  FollowUpsDynamoDbTable:
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: Retain
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "patientId"
          AttributeType: "S"
        - AttributeName: "followUpId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "patientId"
          KeyType: "HASH"
        - AttributeName: "followUpId"
          KeyType: "RANGE"
      TableName: ${file(./sls/variables.yml):${self:provider.stage}.FOLLOWUPS_TABLE}
